# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotedb', '0007_auto_20160116_1554'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='quote',
            name='tags',
            field=models.ManyToManyField(blank=True, to='quotedb.Tag'),
        ),
    ]
